[terminal]
vt = "7"

[general]
# for autologin but not greeter
#service = "login"

# for greeter but not autologin
service = "cosmic-greeter"

[default_session]
# for autologin but not greeter
#command = "start-cosmic > ~/.session-errors"
#user = "guest"

# for greeter but not autologin
command = "cosmic-greeter-start"
user = "cosmic-greeter"
